bdk:
  host: develop2.symphony.com
  bot:
    username: gdrive-bot
    privateKey:
      path: rsa/privatekey.pem

logging:
  level:
    com.symphony: info

spring:
  jmx.enabled: false
  main.banner-mode: off

gdrive-bot.host: localhost
